ALTER TABLE workerstats
  ADD COLUMN IF NOT EXISTS validshares BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS invalidshares BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS foundblocks BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS difficulty DOUBLE PRECISION NULL;